### ISSUE TITLE
How to recover the connection from the link blockage?

### ISSUE THREAD

**Issue by zihaofeng2001** [tapparelj/gr-lora_sdr#107]
Hi,

Thanks for your code. I have successfully implemented this repo but just encountered a problem: sometimes when the connection was suddenly blocked, we couldn't recover the connection even though the link was recovered again, and the terminal showed the Python exception below:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/**/miniconda3/envs/gr310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/**/miniconda3/envs/gr310/lib/python3.10/site-packages/gnuradio/grc/gui/Executor.py", line 115, in run
    r = self.process.stdout.read(1)
  File "/home/**/miniconda3/envs/gr310/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 9: invalid continuation byte
```

Do you know how to solve this? Looking forward to your reply~

**Comment by tapparelj** [comment]
Hi @zif004,
as the error mention the GUI component, are you printing data in the GUI?
If not, are you running the code directly in gnuradio-companion or from a terminal?

**Comment by tapparelj** [comment]
As there has been no follow up for some time I will close this issue.
Do not hesitate to reopen it if needed.
